# You can override the included template(s) by including variable overrides
# SAST customization: https://docs.gitlab.com/ee/user/application_security/sast/#customizing-the-sast-settings
# Secret Detection customization: https://docs.gitlab.com/ee/user/application_security/secret_detection/#customizing-settings
# Dependency Scanning customization: https://docs.gitlab.com/ee/user/application_security/dependency_scanning/#customizing-the-dependency-scanning-settings
# Container Scanning customization: https://docs.gitlab.com/ee/user/application_security/container_scanning/#customizing-the-container-scanning-settings
# Note that environment variables can be set in several places
# See https://docs.gitlab.com/ee/ci/variables/#cicd-variable-precedence
image: gcc
build:
  stage: build
  script:
  - touch configure aclocal.m4 Makefile.in src/Makefile.in
    doc/Makefile.in config.h.in && sleep 1 && ./configure && touch doc/libhideip.info
    && sleep 1 && make
stages:
- test
- build
sast:
  stage: test
include:
- template: Security/SAST.gitlab-ci.yml
