#install: skip

language: c

#compiler:
#        - gcc
#        - clang

os:
        - linux
        - osx
        - freebsd

branches:
        - dev

script: ./configure --enable-public-interface && make

