#install: skip

language: c

#compiler:
#        - gcc
#        - clang

os:
        - linux
        - osx
        - freebsd

branches:
        - dev

script: touch configure aclocal.m4 Makefile.in src/Makefile.in doc/Makefile.in config.h.in doc/libhideip.info && grep -R u_int /usr/include && ./configure --enable-public-interface && make

